version: '2'

services:
  ember:
    image: danlynn/ember-cli:4.4.0-node_16.15
    build: -
    command: ember test
    volumes:
      - .:/app
    tmpfs:
      - /myapp/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"