name: Build, Test and Deploy with Docker

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://docker:19.03.13
        args: build .
      - uses: docker://docker:19.03.13
        args: run --rm ember
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}