name: Build, Test and Deploy with Docker

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
      - uses: docker://docker:20.10.17
        with:
          args: build . --tag consulta-guru
      - name: Test
      - uses: docker://docker:20.10.17
        with:
          args: run --rm danlynn/ember-cli:4.4.0-node_16.15
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}