name: Build and Deploy with Docker

on:
  push:
    branches: [ main ]
    
  # Run workflow manually
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build . --file Dockerfile --tag consulta-guru
      - uses: actions/checkout@v3
      - name: Run docker image
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: docker run -e FIREBASE_TOKEN=$FIREBASE_TOKEN consulta-guru